u1 = User.create(email: "a@a.com", username: "ant", password: "password")
a1 = Album.create(owner_id: u1.id, name: "album1")
p1 = Photo.create(url: "www.pic", name: "photo1", album_id: a1.id)
p2 = Photo.create(url: "www.pic1", name: "photo2", album_id: a1.id)
p3 = Photo.create(url: "www.pic2", name: "photo3", album_id: a1.id)
p4 = Photo.create(url: "www.pic3", name: "photo4", album_id: a1.id)
p5 = Photo.create(url: "www.pic4", name: "photo5", album_id: a1.id)
